workspace/view/member/urls.py
from django.contrib import admin
from django.urls import path, include

from member.views import MemberJoinView, MemberLoginView, MemberLogoutView

app_name = 'member'

urlpatterns = [
    path('join/', MemberJoinView.as_view(), name='join'),
    path('login/', MemberLoginView.as_view(), name='login'),
    path('logout/', MemberLogoutView.as_view(), name='logout'),
]




# TeaPlateView는 누가 만들어 놓은거다
# path('', TemplateView.as_view(template_name='main.html'))

workspace/view/post/urls.py
from django.urls import path

from post.views import PostWriteView, PostDetailView, PostUpdateView, PostDeleteView, PostListView, PostListAPI

app_name = 'post'

urlpatterns = [
    path('write/', PostWriteView.as_view(), name='write'),
    path('detail/', PostDetailView.as_view(), name='detail'),
    path('update/', PostUpdateView.as_view(), name='update'),
    path('delete/', PostDeleteView.as_view(), name='delete'),
    path('list/', PostListView.as_view(), name='list'),
    path('list/<int:page>/', PostListAPI.as_view(), name='list-api'),
]

workspace/view/view/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from main.views import MainView
from post.views import PostListView
from product.views import ProductDetailView
from view.views import StudentRegisterView, StudentResultView, StudentRegisterFormView, MemberRegisterFormView, \
    MemberRegisterView, UserCalculatorViewForm, UserCalculatorView, UserResultView, PlaceTravelViewForm, \
    PlaceTravelResultView, PlaceTravelView, ProductInfoAPI, MemberResultView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('post/', include('post.urls')),
    # path('product/', include('product.urls')),
    # path('products/', include('product.urls')),
    path('student/register/form/', StudentRegisterFormView.as_view(), name='student-register-form'),
    path('student/register/', StudentRegisterView.as_view(), name='student-register'),
    path('student/result/', StudentResultView.as_view(), name='student-result'),
    path('member/register/form/', MemberRegisterFormView.as_view(), name='member-register-form'),
    path('member/register/', MemberRegisterView.as_view(), name='member-register'),
    path('member/result/', MemberResultView.as_view(), name='member-result'),
    path('product/detail/', ProductDetailView.as_view(), name='product-detail'),
    # path('products/<int:product_id>', ProductDetailAPI.as_view(), name='product-detail'),
    path('', MainView.as_view()),
]

workspace/view/main/models.py
from django.db import models

# Create your models here.

workspace/view/main/views.py
from django.shortcuts import render
from django.views import View


class MainView(View):
    def get(self, request):
        # try:
        #     member = request.session['member']
        # except KeyError:
        #     member = None
        # return render(request, 'main.html', {'member': member})
        return render(request, 'main.html')

workspace/view/templates/main.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>메인</title>
</head>
<body>
    {% if request.session.member %}
        <a href="/member/logout/">로그아웃</a>
    {% else %}
        <a href="{% url 'member:join' %}">회원가입</a>
    {% endif %}
    <h1>메인 페이지</h1>
{#    <h1>{{ member.member_name }}님 환영합니다.</h1>#}
    <h1 id="intro"></h1>

</body>
<script>
    {# 위에서 저렇게 쓰거나 아래서 자바스크립트로 쓰는게 좋다.   #}
    const member_name = `{{ member.member_name }}`;
    if(member_name){
        document.getElementById("intro").innerText = `${member_name}님 환영합니다.`;
    }

</script>
</html>