workspace/view/member/urls.py
from django.contrib import admin
from django.urls import path, include

from member.views import MemberJoinView, MemberLoginView, MemberLogoutView

app_name = 'member'

urlpatterns = [
    path('join/', MemberJoinView.as_view(), name='join'),
    path('login/', MemberLoginView.as_view(), name='login'),
    path('logout/', MemberLogoutView.as_view(), name='logout'),
]




# TeaPlateView는 누가 만들어 놓은거다
# path('', TemplateView.as_view(template_name='main.html'))

workspace/view/post/urls.py
from django.urls import path

from post.views import PostWriteView, PostDetailView, PostUpdateView, PostDeleteView, PostListView, PostListAPI

app_name = 'post'

urlpatterns = [
    path('write/', PostWriteView.as_view(), name='write'),
    path('detail/', PostDetailView.as_view(), name='detail'),
    path('update/', PostUpdateView.as_view(), name='update'),
    path('delete/', PostDeleteView.as_view(), name='delete'),
    path('list/', PostListView.as_view(), name='list'),
    path('list/<int:page>/', PostListAPI.as_view(), name='list-api'),
]

workspace/view/view/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from main.views import MainView
from post.views import PostListView
from product.views import ProductDetailView
from view.views import StudentRegisterView, StudentResultView, StudentRegisterFormView, MemberRegisterFormView, \
    MemberRegisterView, UserCalculatorViewForm, UserCalculatorView, UserResultView, PlaceTravelViewForm, \
    PlaceTravelResultView, PlaceTravelView, ProductInfoAPI, MemberResultView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('post/', include('post.urls')),
    # path('product/', include('product.urls')),
    # path('products/', include('product.urls')),
    path('student/register/form/', StudentRegisterFormView.as_view(), name='student-register-form'),
    path('student/register/', StudentRegisterView.as_view(), name='student-register'),
    path('student/result/', StudentResultView.as_view(), name='student-result'),
    path('member/register/form/', MemberRegisterFormView.as_view(), name='member-register-form'),
    path('member/register/', MemberRegisterView.as_view(), name='member-register'),
    path('member/result/', MemberResultView.as_view(), name='member-result'),
    path('product/detail/', ProductDetailView.as_view(), name='product-detail'),
    # path('products/<int:product_id>', ProductDetailAPI.as_view(), name='product-detail'),
    path('', MainView.as_view()),
]

workspace/view/post/models.py
from django.db import models

from member.models import Member
from post.managers import PostManager


class Post(models.Model):
    post_title = models.CharField(max_length=50, null=False, blank=False)
    post_content = models.CharField(max_length=3000, null=False, blank=False)
    post_view_count = models.BigIntegerField(null=False, default=0)
    post_status = models.BooleanField(default=True)
    member = models.ForeignKey(Member, on_delete=models.PROTECT)

    objects = models.Manager()
    enabled_objects = PostManager()

    class Meta:
        db_table = 'tbl_post'
        ordering = ['-id']

    def get_absolute_url(self):
        return f'/post/detail/{self.id}'

class PostFile(models.Model):
    post = models.ForeignKey(Post, on_delete=models.PROTECT, null=False)
    path = models.ImageField(null=False, blank=False, upload_to='post/%Y/%m/%d/')

    class Meta:
        db_table = 'tbl_post_file'

workspace/view/post/views.py
import math

from django.db import transaction
from django.db.models import F
from django.shortcuts import render, redirect
from django.views import View
from rest_framework.response import Response
from rest_framework.views import APIView

from member.models import Member
from post.models import Post, PostFile
from post.serilaizers import PostSerializer


class PostWriteView(View):
    def get(self, request):
        return render(request, 'post/write.html')

    @transaction.atomic
    def post(self, request):
        data = request.POST
        file = request.FILES

        member = Member(**request.session['member'])

        data = {
            'post_title': data['post-title'],
            'post_content': data['post-content'],
            'member': member
        }
        post = Post.objects.create(**data)

        for key in file:
            PostFile.objects.create(post=post, path=file[key])

        return redirect(post.get_absolute_url())


class PostDetailView(View):
    def get(self, request):
        post = Post.objects.get(id=request.GET['id'])

        post.post_view_count += 1
        post.save(update_fields=['post_view_count'])

        context = {
            'post': post,
            'post_file': list(post.postfile_set.all())
        }
        return render(request, 'post/detail.html', context)


class PostUpdateView(View):
    def get(self, request):
        post = Post.objects.get(id=request.GET['id'])
        return render(request, "post/update.html", {'post': post})

    def post(self, request):
        data = request.POST

        post_id = data['id']
        post = Post.objects.get(id=post_id)

        post.post_title = data['post-title']
        post.post_content = data['post-content']
        post.save(update_fields=['post_title', 'post_content'])

        return redirect(post.get_absolute_url())


class PostDeleteView(View):
    def get(self, request):
        Post.objects.filter(id=request.GET['id']).update(post_status=False)
        # post = Post.objects.get(id=request.GET['id'])
        # post.status = False
        # post.save(update_fields=['status'])
        return redirect('/post/list')


class PostListView(View):
    def get(self, request):
        return render(request, 'post/list.html')

class PostListAPI(APIView):
    def get(self, request, page):
        row_count = 5

        offset = (page - 1) * row_count
        limit = page * row_count


        # API 쓸때는 항상 딕셔너리 상태 values()를 써서 나타내자
        # http://127.0.0.1:8000/post/list/1/

        columns = [
            'id',
            'post_title',
            'post_content',
            'post_view_count',
            'member_name'
        ]
        posts = Post.enabled_objects \
                    .annotate(member_name=F('member__member_name')) \
                    .values(*columns)[offset:limit]

        has_next = Post.enabled_objects.filter()[limit:limit + 1].exists()

        post_info = {
            'posts': posts,
            'hasNext': has_next
        }

        return Response(post_info)

workspace/view/templates/post/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'public/css/header.css' %}">
    {% block static %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{#    {% if request.session.member %}#}
{#        {% include 'fix/header1.html' %}#}
{#    {% elif 조건식 %}#}
{#        {% include 'fix/header2.html' %}#}
{#    {% else %}#}
{#        {% include 'fix/header3.html' %}#}
{#    {% endif %}#}
    {% include 'fix/header.html' %}
    {% block content %}{% endblock %}
</body>
    {% block js %}{% endblock %}
</html>

workspace/view/templates/post/detail.html
{% extends 'post/base.html' %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'post/css/table.css' %}">
{% endblock %}

{% block title %}LIST{% endblock %}

{% block content %}
    <table>
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>조회수</th>
        </tr>
    </table>
    <button id="more">더보기</button>
{% endblock %}

{% block js %}
    <script src="{% static 'post/js/list.js' %}"></script>
{% endblock %}

workspace/view/templates/post/list.html
{% extends 'post/base.html' %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'post/css/table.css' %}">
{% endblock %}

{% block title %}LIST{% endblock %}

{% block content %}
<table>
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>조회수</th>
        </tr>
    </table>
    <button id="more">더보기</button>
{% endblock %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>LIST</title>
    <style>
      

    </style>
</head>
<body>
    
</body>
<script>
    
</script>
</html>

workspace/view/templates/post/update.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'post/css/header.css'%}">
    <title>POST-UPDATE</title>
</head>
<body>
     <header>
        <div>
            <div>
                <p>
                    <strong>{{ request.session.member.member_name }}님 환영합니다😍</strong>
                </p>
            </div>
            <div>
                <a href="{% url 'member:logout' %}">로그아웃</a>
            </div>
        </div>
    </header>
    <form action="{% url 'post:write' %}" method="post" name="write-form">
        {% csrf_token %}
        <input type="text" name="post-title" placeholder="게시글 제목">
        <p>업데이트 내용</p>
        <textarea name="post-content" cols="30" rows="10" style="resize: none"></textarea>
        <button>완료</button>
    </form>
</body>
</html>

workspace/view/templates/post/write.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'post/css/header.css'%}">
    <title>POST-WRITE</title>
</head>
<body>
    <header>
        <div>
            <div>
                <p>
                    <strong>{{ request.session.member.member_name }}님 환영합니다😍</strong>
                </p>
            </div>
            <div>
                <a href="{% url 'member:logout' %}">로그아웃</a>
            </div>
        </div>
    </header>
    {#  장고 템플릿에 있는 url 문법을 쓰쟈 urls에 있음  #}
    <form action="{% url 'post:write' %}" method="post" name="update-form" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="post-title" placeholder="게시글 제목">
        <p>게시글 내용</p>
        <textarea name="post-content" cols="30" rows="10" style="resize: none"></textarea>
        <input type="file" name="upload-file">
        <button>완료</button>
    </form>
</body>
</html>